{% set name = "trame-pyvista" %}
{% set version = "0.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 13d2c5d6fb58562891372a3638f40ea88f39d4e4414de927ee797e7907244233

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - packaging
    - pyvista >=0.48
    - trame >=2.5.2,<3.13.3
    - trame-client >=2.12.7,<3.13.3
    - trame-common <1.2.5
    - trame-server >=2.11.7,!=3.7.*,!=3.8.0,<3.12.6
    - trame-vtk >=2.5.8,!=2.10.3,!=2.11.0,!=2.11.1,!=2.11.2,!=2.11.3,!=2.11.4,!=2.11.5,!=2.11.6,!=2.11.9,!=2.11.10,!=2.11.11,!=2.11.12,!=2.11.13,!=2.11.14,<2.11.17
    - trame-vuetify >=2.3.1,!=3.2.3,!=3.2.4,<3.2.6

test:
  imports:
    - trame
    - trame_pyvista
  commands:
    - pip check
    - python -c "import trame_pyvista; assert trame_pyvista.__version__ == '{{ version }}', trame_pyvista.__version__"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyvista/trame-pyvista
  summary: Trame interface for PyVista
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
